### ISSUE TITLE
Forester new and  transclude_new get "error[Reporter.Message.Parse_error]"

### ISSUE THREAD

**Issue by kkanarios32** [kentookura/forester.nvim#39]
When using Forester new or transclude_new I get a new file created with "error[Reporter.Message.Parse_error]". Any idea why this might be the case?

**Comment by kentookura** [comment]
I think this is because forester still reports some errors on stdout, which gets captured by the plugin. Can you check the output of `forester new --prefix=<pfx> --dest=<dir>`? Also, which version of forester are you on?

**Comment by kkanarios32** [comment]
Yeah, there was an error in my forest that was being output prior to the created tree name. I fixed it.

**Comment by kentookura** [comment]
This is still an implementation error. I haven't taken a look at what the issue exactly is (if the plugin captures stderr or if forester emits errors on stdout), but as long as this isn't fixed, I would keep this open for discoverability. Eventually all these features will get replaced by the LSP.
